---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret
default_redirection_url: https://api.example.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldap://192.168.88.11
    timeout: 5s
    start_tls: false
    tls:
      server_name: ldap.explabs.ru
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: DC=explabs,DC=ru
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: CN=admin,DC=explabs,DC=ru
    password: admin

access_control:
  default_policy: deny
  rules:
    - domain: api.example.com
      policy: one_factor
    - domain: lib.example.com
      policy: one_factor
    - domain: traefik.example.com
      policy: one_factor
    - domain: kibana.example.com
      policy: bypass


session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt